### ISSUE TITLE
cairo vs opencv

### ISSUE THREAD

**Issue by bayethiernodiop** [faustomorales/keras-ocr#10]
Hello, thanks for this great tool, In the original example on Keras Cairo was used to  generate datasets, I just want to know why change to OpenCV

**Comment by faustomorales** [comment]
`cairo` is used in the Keras OCR example primarily for rendering text on images to create synthetic datasets. Originally, `keras-ocr` did the same thing (you can see it if you go back in time).

https://github.com/faustomorales/keras-ocr/blob/5b074c32f4f3e2b9ec24b4ed67495a1e96e0734f/keras_ocr/tools.py#L196

In fact, the early version (prior to the first public commit) of this library directly cited the OCR example.

Today, this library uses `Pillow` (`PIL`) to carry out this task. The benefits for switching were:
- `PIL` has no additional system dependencies that users have to install (or at least none that are unusual for users to have installed already) with `apt`, `brew` or some other system package manager.
- `PIL` has a simpler API than `cairo`
- The quality of images rendered with `PIL` are roughly the same as those rendered with `cairo` in my brief testing.
- `PIL` makes it easy to load fonts from TrueType font files without the fonts needing to be installed on the system (`cairo` required fonts to be installed).

OpenCV is used for generic image manipulation (resizing, warping text boxes, etc.). For generating synthetic data, it is used in conjunction with PIL (which carries out the text rendering steps). It's used here because it is well-supported, ships with pre-built wheels for all major platforms, and has bindings available for other languages (e.g., [JavaScript](https://www.npmjs.com/package/opencv4nodejs)). By doing image processing in OpenCV, it leaves the door open to using the models built with this package with, for example, TensorFlow.js. Some of the post-processing steps in the detector (e.g., extracting contours) cannot be easily done with TensorFlow.js alone. But because all the logic is written with OpenCV functions, porting said logic over to JavaScript will be much easier than if we had used `PIL` for those steps.

We don't use OpenCV for rendering text only because it does not have the same font handling options as `PIL`.

**Comment by bayethiernodiop** [comment]
Awesome. thanks for the clear explanations. YOU ROCK!!!
