### ISSUE TITLE
advice on building dataset for generique OCR

### ISSUE THREAD

**Issue by bayethiernodiop** [faustomorales/keras-ocr#15]
Hi everyone, some guidelines or links on how to generate a dataset for a generic OCR, I am concerned more in the background part. Also, what would be the "maximum" mean edit distance of an OCR model that is used in production.

**Comment by faustomorales** [comment]
@bayethiernodiop I think the answers to these questions will depend entirely on the use case. For example, if your use case is for paper documents, backgrounds can be very simple and you likely desire a very small edit distance. Because this question is not actually a problem with the code or a request for a feature, I will close this issue for now. For feedback on OCR performance requirements, it might be better to discuss the needs with your potential users.
