### ISSUE TITLE
annotate() missing 1 required positional argument: 's'

### ISSUE THREAD

**Issue by JL-plusUltra** [faustomorales/keras-ocr#183]
I used the fixed annotated() version  where s=text for an old project I had, but I still get the error that one positional argument is missing. The code works to extract text from one image, but the error stops it from getting the rest. Any help and suggestions would be awesome. Thanks!
Here is a pic:
![c1](https://user-images.githubusercontent.com/90848472/139164122-c19cda3d-5af7-4405-be5c-f7f2bd2aa195.PNG)

**Comment by OmarMohamedHamed** [comment]
I have got the same error, have you solved this problem ?

**Comment by jjb21** [comment]
's' is a deprecated synonym for the 'text' parameter that is used in the keras_ocr.tools.drawAnnotations () funtion.

**Comment by shayeny** [comment]
Facing the same issue. Is there a fix planned for this ?

**Comment by faustomorales** [comment]
If you're getting `annotate() missing 1 required positional argument: 's' `, it means you are on an old version of `matplotlib` because the parameter changed from `s` to `text` in matpllib [v3.3.0](https://matplotlib.org/3.3.0/api/api_changes.html#axes-annotate-and-pyplot-annotate-parameter-name-changed).

To fix this, you have two options:

- Upgrade `matplotlib` to >= 3.3.0, which supports the new `text` parameter. 
- Downgrade`keras-ocr` to <= v0.8.7, which uses the older `s` parameter.

**Comment by FatmAhmedM** [comment]
@faustomorales thanks,that was helpful

**Comment by shayeny** [comment]
Worked like a charm! Thanks @faustomorales

**Comment by ebayo** [comment]
The change from ```s``` to ```text``` seems to have been revoked in [newer versions](https://github.com/matplotlib/matplotlib/pull/12383). 

I got the error stated in the issue using ```matplotlib==3.2.2```

It work well when I downgraded to ```matplotlib==3.0.0```

**Comment by mrdbourke** [comment]
Using Google Colab (as of August 16 2022):

* `s` works, `text` does not (`matplotlib==3.2.2`)

On my local machine:

* `text` works, `s` does not (`matplotlib==3.5.1`)
