### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by Johndirr** [faustomorales/keras-ocr#24]
Hi, I was just running the old example code from some versions before with the current release (this time under windows):
```
import matplotlib.pyplot as plt

import keras_ocr

# keras-ocr will automatically download pretrained
# weights for the detector and recognizer.
pipeline = keras_ocr.pipeline.Pipeline()

image = keras_ocr.tools.read('test7.png')

# Predictions is a list of (text, box) tuples.
predictions = pipeline.recognize(image)

# Plot the results.
fig, ax = plt.subplots()
ax.imshow(keras_ocr.tools.drawBoxes(image, predictions, boxes_format='predictions'))
for text, box in predictions:
    ax.annotate(s=text, xy=box[0], xytext=box[0] - 50, arrowprops={'arrowstyle': '->'})
    print(text)
plt.show()
```

It seems to not work anymore. It errors out on line 12 (predictions = ...) with the error:

>   File "bla.py", line 12, in <module>
>     predictions = pipeline.recognize(image)
>   File "C:\Users\RetroHelix\Envs\test\lib\site-packages\keras_ocr\pipeline.py", line 55, in recognize
>     box_groups = self.detector.detect(images=images, **detection_kwargs)
>   File "C:\Users\RetroHelix\Envs\test\lib\site-packages\keras_ocr\detection.py", line 647, in detect
>     images = [compute_input(tools.read(image)) for image in images]
>   File "C:\Users\RetroHelix\Envs\test\lib\site-packages\keras_ocr\detection.py", line 647, in <listcomp>
>     images = [compute_input(tools.read(image)) for image in images]
>   File "C:\Users\RetroHelix\Envs\test\lib\site-packages\keras_ocr\detection.py", line 40, in compute_input
>     image -= mean * 255
> ValueError: operands could not be broadcast together with shapes (1280,6) (3,) (1280,6)

I guess something changed and I have to alter the code a bit. Any idea whats wrong?

PS. It would be nice to have super easy examples. Something like "Detect Text Using Pretrained Model", "Recognize Text Using Pretrained Model" and both together. Just with one image.

**Comment by faustomorales** [comment]
The API for `recognize` was changed to support multiple images as of https://github.com/faustomorales/keras-ocr/issues/9.  In this case, if you change `pipeline.recognize(image)` to `pipeline.recognize[image])[0]`, you'll be off to the races. I'm sorry for the breaking change -- I think the API is rapidly stabilizing thanks to the great feedback provided by yourself and others.

I made this change because going from one image to multiple images *efficiently* (i.e., with appropriate batching at each step) is non-trivial for users, so I wanted to make the API handle that for them. The examples all assume multiple images because doing so requires no additional complexity in the example code and is easily adapted to a single image, as the fix above shows.

With regard to examples, I agree with you that it's a good idea to include a detector-only example and a recognizer-only example along with the existing full pipeline example. That said, the examples should all use multiple images, again because it's easy for users to adapt a multi-image example to a single image but it is not as easy to conceptualize doing the reverse. Would you want to send a PR with the added examples in `/docs/examples/using_pretrained_models.rst`?

**Comment by faustomorales** [comment]
I believe the above answer resolves the error you're seeing so I'm closing this issue for now. If it does not resolve your error, please reply here and I will reopen. Thanks!

**Comment by Johndirr** [comment]
Thank you very much for your fast response.
I tried to understand whats happening and it's quite clear now. Because of the change to support multiple images I had to pass a list of images (`pipeline.recognize(image)` to `pipeline.recognize([image])`) and since the output is a list of lists I had to extract the list with `[0]` before passing it to `keras_ocr.tools.drawBoxes` ...

I would very much like to provide examples for the API but never really worked with git and PRs and such :) I added this task to my todo list but even if its not a big deal I will need some time to get to this. Till now I just played around when I got some free time (weekend) to see whats possible.
