### ISSUE TITLE
recognition improvement

### ISSUE THREAD

**Issue by shekarneo** [faustomorales/keras-ocr#30]
hi, how can i improve the recognition accuracy of the noisy images and text with same background, i have attached some examples here 

![tyre](https://user-images.githubusercontent.com/25033310/74313656-fece6500-4d6b-11ea-8fae-082421897241.jpg)
![tyre1](https://user-images.githubusercontent.com/25033310/74313659-ffff9200-4d6b-11ea-907e-89bd0459f275.jpg)

**Comment by faustomorales** [comment]
First, thanks for trying out the package!

Getting detection to work well in this case is relatively easy but improving recognition will take more work. 

On detection, because the text is so small upscaling is very important. The default upscaling of 2x works but because the image is so tall, you hit the default `max_size` limit too soon. I found setting that parameter to 4096 to be enough to get high quality text detection.

```python
import matplotlib.pyplot as plt
import keras_ocr

image = keras_ocr.tools.read(
    'https://user-images.githubusercontent.com/25033310/74313656-fece6500-4d6b-11ea-8fae-082421897241.jpg'
)

pipeline = keras_ocr.pipeline.Pipeline(max_size=4096)
predictions = pipeline.recognize([image])[0]

fig, ax = plt.subplots()
keras_ocr.tools.drawAnnotations(image=image, predictions=predictions, ax=ax)
```
![plotted predictions](https://user-images.githubusercontent.com/9735401/74598424-f3628e80-5036-11ea-9c9a-15460cc62773.jpg)

The bounding boxes look pretty good -- but the text recognition is quite poor. To fix this, I think you'll need to get a dataset together of text that looks like that in your use case to train a custom recognizer.  The good news is that it is much easier to train the recognizer than the detector! There's an [example](https://keras-ocr.readthedocs.io/en/latest/examples/fine_tuning_recognizer.html) for fine tuning the detector in the documentation which I think you may want to adapt.

I'm going to close this now because it is not so much a bug in the package as it is a how-to question which I believe my comments above answer. If you run into problems with the example or with training the recognizer in general, please open a new issue.

**Comment by faustomorales** [comment]
I forgot to run your second example, but that one actually does a little better.

```python
import matplotlib.pyplot as plt
import keras_ocr

image = keras_ocr.tools.read(
    'https://user-images.githubusercontent.com/25033310/74313659-ffff9200-4d6b-11ea-907e-89bd0459f275.jpg'
)
pipeline = keras_ocr.pipeline.Pipeline(max_size=4096)
predictions = pipeline.recognize([image])[0]
fig, ax = plt.subplots()
keras_ocr.tools.drawAnnotations(image=image, predictions=predictions, ax=ax)
```

![second example](https://user-images.githubusercontent.com/9735401/74598468-f1e59600-5037-11ea-9cb1-91aa9599cc45.jpg)

**Comment by shekarneo** [comment]
Hi.

Thanks for your valuable time on this issue.
I tried to generate custom text image generator which has tyre images
background and printed dark text, training went well and it worked for the
same type of images which are generated. But it fails to recognise the real
tyre texts. I think o need to collect the real data rather than text image
generator.

**Comment by faustomorales** [comment]
Yes, that's correct -- it appears that you will need to obtain some real-world labeled data to train the recognizer for this use case.
