### ISSUE TITLE
Could you share the conversion code?

### ISSUE THREAD

**Issue by ALittle-Eve** [faustomorales/keras-ocr#38]
I'd like to know how to convert pth model to h5 model. Could you please share me with this code?Thx

**Comment by faustomorales** [comment]
Hi there -- The code for converting the CRAFT PyTorch weights to Keras h5 weights is already part of the repository. The way we do it is we create the Keras model and then manually load the weights from the PyTorch weights file into that Keras model. Please note that this code is unlikely to generalize to other models. There is a [unit test](https://github.com/faustomorales/keras-ocr/blob/master/tests/test_pytorch_keras.py) in this library to ensure that the conversion works correctly.

https://github.com/faustomorales/keras-ocr/blob/1081806e79df1c9f3cd9162613968c774da65545/keras_ocr/detection.py#L365-L400

I will close this issue now since it is not an actual problem with the library, but please do feel free comment back if this does not answer your question.
