### ISSUE TITLE
Non-English Characters Problem

### ISSUE THREAD

**Issue by sadi-guzel** [faustomorales/keras-ocr#45]
I am trying to train recognizer model with my custom alphabet:

```
alphabet = ''.join(
    [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
     'Y', 'Z',  '[', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w',
     'x', 'y', 'z', '|', 'Ç', 'Ö', 'Ü', 'ç', 'ö', 'ü', 'Ğ', 'ğ', 'İ', 'ı', 'Ş', 'ş'])
recognizer_alphabet = ''.join(sorted(set(alphabet)))
```

And I got the error below:
**_for c in ''.join(sentences)), 'Found illegal characters in sentence.'
AssertionError: Found illegal characters in sentence._**

And these are sentences:
sentences: ['gıda', 'inş. iç v', 'e dış. ti', 'c. ltd.', 'a', 'zie baina', 'a', 'dr']

**Comment by faustomorales** [comment]
Hi @sadi-guzel! Thanks for your question. I think the problem you're having is due to the space (`' '`) character not being included in your alphabet, but it appears in the several of the sentences in your example. If you insert `alphabet += ' '` right after the first line, I believe that should resolve the issue. Let us know how it goes!

**Comment by faustomorales** [comment]
Closing this issue because I think the above comment resolves the issue and no response has been provided. If the problem persists, please comment and we can re-open!
