### ISSUE TITLE
build_params is ignored in Recognizer init method

### ISSUE THREAD

**Issue by cheperuiz** [faustomorales/keras-ocr#56]
Hi,
I think I found a simple bug, `build_params` is ignored when calling 
```
Recognizer(weights=None, alphabet=alphabet, build_params=build_params)
```
Changing the default of the `build_params` kwarg from `None` to `{}` and this change to line 315 would do it, allowing to pass only some keys and keep the defaults for the rest. 
```
build_params = {
                k: build_params.get(k, DEFAULT_BUILD_PARAMS[k]) for k, v in DEFAULT_BUILD_PARAMS.items()
            }
```
TY
...or a cleaner version of that ;)
Cheers!

**Comment by faustomorales** [comment]
Great find! I just pushed 9da08304a1130c176bf1e41a462f24f42b82fe6e which resolves this issue. We can't set the default to `{}` because that would mean using a [mutable default argument](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments). We could still implement something like what you suggest but I think that, for now, it's a little too much magic. You can use the defaults while only changing some values using something like that following.

```python
keras_ocr.recognition.Recognizer(
    alphabet=alphabet,
    weights=None,
    build_params={**keras_ocr.recognition.DEFAULT_BUILD_PARAMS, 'height': 500}
)
```

**Comment by faustomorales** [comment]
If this doesn't fit the need, please comment back and we can re-open.
