### ISSUE TITLE
Custom fine-tune model

### ISSUE THREAD

**Issue by tfilip** [faustomorales/keras-ocr#57]
Is there currently any way of fine-tunning on a different model than the default one? (like passing a .ht file to the recognizer)

Also is there any way of training the recognizer with multiple gpus?

Thank you :)

**Comment by faustomorales** [comment]
Hi @tfilip!

- *Can I train a different model?* In order to supply all the convenience functions, there are a lot of constraints that the architectures must satisfy. You can modify the recognizer and detector architectures somewhat using the keyword arguments (see [API documentation](https://keras-ocr.readthedocs.io/en/latest/api.html#core-detector-and-recognizer) and [examples](https://keras-ocr.readthedocs.io/en/latest/examples/index.html)). For example, on the recognizer, you can select different RNN layers, number of filters, etc. If you wish to submit an amendment to the architecture, please open an issue to discuss your specific change.
- *Can I train the recognizer with multiple GPUs?* A multi-GPU example is provided [here](https://github.com/faustomorales/keras-ocr/blob/master/scripts/train_recognizer_synthtext90_multigpu.py).
