### ISSUE TITLE
Undesired behavior when detecting and recognizing numbers with commas

### ISSUE THREAD

**Issue by ivsanro1** [faustomorales/keras-ocr#64]
Hello. First of all, thanks for this library, it is really useful and even with the problem I'm going to describe, I find the results very good overall

I am working with scanned documents.

I have found that in most scenarios where there's a number with a comma (decimal number), the text detection separates the number at the left of the comma and the one at the right of the comma. I have also found that when this happens, the comma either:

- Falls in the left text box, and it is usually recognized as a "1", or
- Is not detected at all

In this example you can find both behaviors:

![imagen](https://user-images.githubusercontent.com/30293331/79357749-b8021480-7f40-11ea-8742-97ca73f4842e.png)

Maybe this is because training data for text detection is not contemplating these cases?

**Comment by kymillev** [comment]
The pretrained model does not contain commas in its alphabet, so it either doesn't recognize one or recognizes an incorrect character. Retraining the models on some synthetic data with commas probably fixes this issue.

**Comment by faustomorales** [comment]
Thanks for trying out `keras-ocr`!

The above comment is exactly correct (the default alphabet does not include punctuation). If you would like a recognizer with support for punctuation (or perhaps just for commas), I would recommend the [end-to-end](https://keras-ocr.readthedocs.io/en/latest/examples/end_to_end_training.html#) tutorial which includes an example for tuning the recognizer to include more letters and using the data generators to obtain it. You may also wish to use `datasets.get_icdar_2013_recognizer_dataset` to obtain a dataset of real images that I believe includes some punctuation.

I'll close this issue for now as it is an expected behavior but please feel free to comment back if you disagree and wish to discuss further. Thanks!
