### ISSUE TITLE
h5 file to pb

### ISSUE THREAD

**Issue by rawat123** [faustomorales/keras-ocr#77]
hi is there any conversion method to convert h5 file to pb???
or any way we can save the training to .pb file.

Thank you

**Comment by faustomorales** [comment]
The manner in which you would save the model as a protocol buffer varies depending on how you want to use it. For example, if you wish to use TensorFlow Serving, there is a fair amount of work to be done to set up the signature. Speaking generally, though, you can save Keras models using `tf.saved_model.save`.

```python
import tensorflow as tf
import keras_ocr

recognizer = keras_ocr.recognition.Recognizer()
tf.saved_model.save(obj=recognizer.model, export_dir='recognizer')
```

This will create a `saved_model.pb` file in a folder called `recognizer`.

Closing since I think this strictly answers the question but feel free to reply back if it doesn't. Thanks!
