### ISSUE TITLE
Performance on CPU 

### ISSUE THREAD

**Issue by RunshengZhu** [faustomorales/keras-ocr#8]
Thanks for this wonderful work! I've run sample code(use pretrained model) on mac with intel i7 + 16G memory, the result is pretty well, but the performance of pipeline is really poor(over 10min on a 3968x2976 phone image). 
    Also every core of CPU is fully used.Compared with model's performance on both two origin repo, I guess that there should be bottleneck in the pipeline. 
    I wonder if you were tested it on similar system @faustomorales .

**Comment by faustomorales** [comment]
Hi @RunshengZhu -- By default, the pipeline scales the input image by a factor of two. See relevant snippets below.

https://github.com/faustomorales/keras-ocr/blob/6a1590f92867d45467ecfcf134f19b4cc50c3192/keras_ocr/pipeline.py#L14

https://github.com/faustomorales/keras-ocr/blob/6a1590f92867d45467ecfcf134f19b4cc50c3192/keras_ocr/pipeline.py#L36-L38

This means that inference is taking place on an image with four times as many pixels as what you provide. The default is because I anticipated that input images would often have very small characters and upsampling improves text detection (see metrics in the README). This may not be necessary for you, so you may wish to use `keras_ocr.pipeline.Pipeline(scale=1)`. This should yield speed equal or very close to that of using the models on their own.

If you still note a disparity, please reply with some sample code and a sample image to help me reproduce the issue. Thanks!

**Comment by RunshengZhu** [comment]
@faustomorales Thanks for the reply~ The inference speed is much similar to the origin repo.

**Comment by jomen93** [comment]
hi @faustomorales , very nice code!
I have a little question. What is the dataset that was used to create the model crnn_kurapan.h5 ? I wish modify the model
